package giis.demo.util;

import java.awt.EventQueue;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import giis.demo.ui.receptionist.ReceptionistMenu; 


public class SwingMain {

    private JFrame frame;

    /**
     * Launch the application.
     */
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() { //NOSONAR autogenerated code
            public void run() {
                try {
                    SwingMain window = new SwingMain();
                    window.frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace(); //NOSONAR autogenerated code
                }
            }
        });
    }

    /**
     * Constructor that creates the application.
     */
    public SwingMain() {
        initialize();
    }

    /**
     * Initialize the contents of the frame.
     */
    private void initialize() {
        frame = new JFrame();
        frame.setTitle("Hospital");
        frame.setSize(300, 250);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);

        // Use BoxLayout to align components vertically
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        frame.getContentPane().add(panel);

        // Title label
        JLabel lblTitle = new JLabel("Hospital");
        lblTitle.setFont(new Font("Arial", Font.BOLD, 20));
        lblTitle.setAlignmentX(Component.CENTER_ALIGNMENT);
        lblTitle.setBorder(BorderFactory.createEmptyBorder(10, 0, 20, 0));
        panel.add(lblTitle);

        // Receptionist button
        JButton btnReceptionist = new JButton("Receptionist");
        btnReceptionist.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnReceptionist.setFocusPainted(false);
        btnReceptionist.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // ✅ Open Receptionist Menu
                new ReceptionistMenu();
            }
        });
        panel.add(btnReceptionist);

        // Spacing
        panel.add(Box.createRigidArea(new Dimension(0, 10)));

        // Doctor button
        JButton btnDoctor = new JButton("Doctor");
        btnDoctor.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnDoctor.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(frame, "Doctor interface coming soon!");
            }
        });
        panel.add(btnDoctor);

        // Spacing
        panel.add(Box.createRigidArea(new Dimension(0, 10)));

     // === Manager Button ===
        JButton btnManager = new JButton("Manager");
        btnManager.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnManager.setFocusPainted(false);

        // Action to open ManagerWindow
        btnManager.addActionListener(e -> 
            SwingUtilities.invokeLater(() -> new giis.demo.ui.manager.ManagerWindow())
        );

        panel.add(Box.createVerticalStrut(10)); // Adds spacing before the button
        panel.add(btnManager);

    }

    public JFrame getFrame() {
        return this.frame;
    }
}
